name: Quality

on:
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint
        run: pnpm lint

  prettier:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Prettier
        run: pnpm format:check

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Type
        run: pnpm typecheck
